// Generated by gencpp from file define_msg_pkg/msg_data.msg
// DO NOT EDIT!


#ifndef DEFINE_MSG_PKG_MESSAGE_MSG_DATA_H
#define DEFINE_MSG_PKG_MESSAGE_MSG_DATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace define_msg_pkg
{
template <class ContainerAllocator>
struct msg_data_
{
  typedef msg_data_<ContainerAllocator> Type;

  msg_data_()
    : data(0)  {
    }
  msg_data_(const ContainerAllocator& _alloc)
    : data(0)  {
  (void)_alloc;
    }



   typedef uint32_t _data_type;
  _data_type data;




  typedef boost::shared_ptr< ::define_msg_pkg::msg_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::define_msg_pkg::msg_data_<ContainerAllocator> const> ConstPtr;

}; // struct msg_data_

typedef ::define_msg_pkg::msg_data_<std::allocator<void> > msg_data;

typedef boost::shared_ptr< ::define_msg_pkg::msg_data > msg_dataPtr;
typedef boost::shared_ptr< ::define_msg_pkg::msg_data const> msg_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::define_msg_pkg::msg_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::define_msg_pkg::msg_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace define_msg_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'define_msg_pkg': ['/home/lmf/ross/src/define_msg_pkg/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::define_msg_pkg::msg_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::define_msg_pkg::msg_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::define_msg_pkg::msg_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::define_msg_pkg::msg_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::define_msg_pkg::msg_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::define_msg_pkg::msg_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::define_msg_pkg::msg_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "304a39449588c7f8ce2df6e8001c5fce";
  }

  static const char* value(const ::define_msg_pkg::msg_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x304a39449588c7f8ULL;
  static const uint64_t static_value2 = 0xce2df6e8001c5fceULL;
};

template<class ContainerAllocator>
struct DataType< ::define_msg_pkg::msg_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "define_msg_pkg/msg_data";
  }

  static const char* value(const ::define_msg_pkg::msg_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::define_msg_pkg::msg_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 data\n\
";
  }

  static const char* value(const ::define_msg_pkg::msg_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::define_msg_pkg::msg_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msg_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::define_msg_pkg::msg_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::define_msg_pkg::msg_data_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEFINE_MSG_PKG_MESSAGE_MSG_DATA_H
